//  Lables
export const GET_LABLES = 'GET_LABLES';
export const GET_LABLES_SUCCESS = 'GET_LABLES_SUCCESS';
export const GET_LABLES_FAILURE = 'GET_LABLES_FAILURE';

//  Data
export const GET_USERS_DATA = 'GET_USERS_DATA';
export const GET_USERS_DATA_SUCCESS = 'GET_USERS_DATA_SUCCESS';
export const GET_USERS_DATA_FAILURE = 'GET_USERS_DATA_FAILURE';
